# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='img_url',
        ),
        migrations.AddField(
            model_name='movement',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='movement_image'),
        ),
    ]
