# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-19 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20170119_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='image',
            field=models.ImageField(default='default.png', upload_to='movement_image'),
        ),
    ]
